# Minimal BACnet Device Configuration Example
# Use this as a template for creating simple test devices

device:
  name: "Minimal Test Device"
  instance: 2000
  description: "Simple BACnet device with basic objects"
  vendor_id: 999
  model: "Minimal Simulator"

network:
  address: "0.0.0.0"
  port: 47808

objects:
  # One temperature sensor
  - type: analog-value
    instance: 1
    name: "Room_Temperature"
    initial_value: 21.0
    units: "degreesCelsius"
    description: "Room temperature"
    simulate: true
    simulation:
      type: random
      interval: 5.0
      min: 18.0
      max: 26.0
  
  # One binary status
  - type: binary-value
    instance: 1
    name: "Occupancy"
    initial_value: 0
    description: "Room occupied status"
    simulate: true
    simulation:
      type: random
      interval: 30.0
  
  # One writable output
  - type: analog-output
    instance: 1
    name: "Setpoint"
    initial_value: 22.0
    units: "degreesCelsius"
    description: "Temperature setpoint"
    simulate: false

