# BACnet Device Simulator Configuration for Network Testing
# This config is optimized for discovery across WiFi network

# Device settings
device:
  name: "BACnet WiFi Test Device"
  instance: 1001
  description: "Network BACnet Simulator - Discoverable on WiFi"
  vendor_id: 999
  model: "Virtual BACnet Simulator v1.0"

# Network settings - configured for your WiFi network
network:
  # Your Mac's network IP: 192.168.29.200
  # Subnet mask /24 allows broadcast to 192.168.29.255
  address: "192.168.29.200/24"
  port: 47808

# BACnet objects to create - simplified for testing
objects:
  # Temperature sensor
  - type: analog-value
    instance: 1
    name: "Temperature"
    initial_value: 22.5
    units: "degreesCelsius"
    description: "Room temperature sensor"
    simulate: true
    simulation:
      type: sine
      interval: 5.0
      amplitude: 5.0
      offset: 22.0
      frequency: 0.02
  
  # Humidity sensor
  - type: analog-value
    instance: 2
    name: "Humidity"
    initial_value: 45.0
    units: "percentRelativeHumidity"
    description: "Room humidity sensor"
    simulate: true
    simulation:
      type: random
      interval: 10.0
      min: 30.0
      max: 70.0
  
  # Setpoint control
  - type: analog-output
    instance: 1
    name: "Temperature_Setpoint"
    initial_value: 21.0
    units: "degreesCelsius"
    description: "Temperature setpoint"
    simulate: false
  
  # Fan status
  - type: binary-value
    instance: 1
    name: "Fan_Status"
    initial_value: 0
    description: "Fan on/off"
    simulate: true
    simulation:
      type: toggle
      interval: 30.0
  
  # Operating mode
  - type: multi-state-value
    instance: 1
    name: "HVAC_Mode"
    initial_value: 1
    number_of_states: 4
    state_text: ["Off", "Cool", "Heat", "Auto"]
    description: "HVAC operating mode"
    simulate: true
    simulation:
      type: cycle
      interval: 60.0

